// <auto-generated />
namespace FlexRental.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class inventoryView : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inventoryView));
        
        string IMigrationMetadata.Id
        {
            get { return "201504130217365_inventoryView"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
